services:
  backend:
    build: ./backend
    container_name: picshare-backend
    volumes:
      - ./backend/data:/app/data:z
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - 8000:8000
    hostname: picshare-backend
    mem_limit: 4G
    cpu_count: 2

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
        - BACKEND_HOSTNAME=${BACKEND_HOSTNAME}
    container_name: picshare-frontend
    ports:
      - "3005:3000"
    depends_on:
      - backend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - BACKEND_HOSTNAME=picshare-backend:8000
# Define named volumes if you prefer, but host-binding is simpler for VPS deployments
# volumes:
#   backend_data: